FROM elasticsearch:2.3

#Mantenidor del dockerfile
MAINTAINER Kevin

#Instalació d'un editor de text
RUN apt-get update
RUN apt-get -y install vim

#Plugin afegit per a disposar d'entorn grafic d'elasticsearch
RUN plugin install mobz/elasticsearch-head 

